import type { Metadata } from "next";
import "@/assets/styles/globals.css";
import Header from "@/components/Header/Index";
import { Plus_Jakarta_Sans } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const jakata = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["200", "800", "600"],
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jakata.className}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
